### PR TITLE
Sandeep

### PR DESCRIPTION
**Pull request by phalodi**
dynamic reactive mongo connector and code refactor

### CODE REVIEW

**Comment by gupta-himanshu** [comment]
@phalodi Change the name of:
"location" -> "host"
"database" -> "dbName"

and for now remove the collection name from the connector. Connector should return only the connection  object.

**Comment by phalodi** [comment]
i had make changes as mentioned and also make changes in test case corresponding to it.
So pls review the code

**Comment by phalodi** [comment]
i add my updated code including authentication and number of channels so please review it

**Comment by gupta-himanshu** [comment]
@phalodi Replace -  
"val db = connection(dbName)
db"
with 
"connection(dbName)"

**Comment by phalodi** [comment]
Done!!

**Comment by gupta-himanshu** [comment]
@phalodi I cannot see the change yet.

**Comment by phalodi** [comment]
may be some problem i again pushed it....check it out

**Comment by gupta-himanshu** [comment]
@phalodi Okay got it.

**Comment by gupta-himanshu** [comment]
@phalodi Please delete this branch now.

**Pull request merged**
