### PR TITLE
Pushpendu

### PR DESCRIPTION
**Pull request by pushpendupurkait**
All unnecessary files from repository, ready to merge.

### CODE REVIEW

**Comment by gupta-himanshu** [comment]
@pushpendupurkait What is the use of file "log4j2.xml" ? Can we replace it with "logback.xml" ?

**Comment by gupta-himanshu** [comment]
@pushpendupurkait Please separate out the dependencies in different variables along with their Versions.

**Comment by gupta-himanshu** [comment]
@pushpendupurkait Is @phalodi is working on ReactiveMongo connector ?

**Comment by pushpendupurkait** [comment]
We need log4j2.xml file for reactive mongo to use default configuration.

**Comment by gupta-himanshu** [comment]
@pushpendupurkait Okay, for now we can keep log4j2.xml. But, we have to also see its compatibility with logback.xml.

**Comment by gupta-himanshu** [comment]
@pushpendupurkait Are the dependencies been pulled out ?

**Pull request closed without merging**
