### PR TITLE
Sandeep

### PR DESCRIPTION
**Pull request by phalodi**

### CODE REVIEW

**Comment by phalodi** [comment]
we push some code snippet so please review it and let us know if anything need to refactor or change

**Comment by gupta-himanshu** [comment]
@phalodi Provide DBCrud operations with Case Class type as input.

**Comment by gupta-himanshu** [comment]
@phalodi Replace 
"val future = coll.insert(conPerson)
 future.map"
with 
"coll.insert(conPerson).map"
for every CRUD function.

**Comment by gupta-himanshu** [comment]
@phalodi Find a more appropriate check for updated/inserted documents.

**Comment by phalodi** [comment]
@gupta-himanshu i refactor the code as u mention above and add set operator and multi in the update method.

**Comment by gupta-himanshu** [comment]
@phalodi The code is not in condition to be merged. So, I am closing this pull request.

**Pull request closed without merging**
