### PR TITLE
Pushpendu

### PR DESCRIPTION
**Pull request by pushpendupurkait**

### CODE REVIEW

**Comment by gupta-himanshu** [comment]
@pushpendupurkait Please move Twitter Credentials in **Sample** itself.

**Comment by gupta-himanshu** [comment]
@pushpendupurkait Why all the modules are dependent on **dbs** ? Are we using **dbs** servcies in all modules ?

**Comment by gupta-himanshu** [comment]
@pushpendupurkait Why **samples** module is defined as only project ? Is it not using any settings of the parent project ? Or it has its own separate settings ?

**Comment by pushpendupurkait** [comment]
samples project has its own build.sbt file, i have added dependencies in that build.sbt file.

**Comment by gupta-himanshu** [comment]
@pushpendupurkait That's okay. Can you point me to the **samples** project settings (not dependencies) ?

**Comment by pushpendupurkait** [comment]
streaming sub-project is using dbs while inserting stream data to reactiveMongo.
dataProcess sub project is using dbs to get collection form reactiveMongo.

**Pull request closed without merging**
