### PR TITLE
Sandeep

### PR DESCRIPTION
**Pull request by phalodi**

### CODE REVIEW

**Comment by gupta-himanshu** [comment]
@phalodi please correct the package in **dataProcess/src/main/scala/dataProcess/ShowData.scala** file.

**Comment by gupta-himanshu** [comment]
@phalodi Can we add a File Appender in **logback.xml** ?

**Comment by gupta-himanshu** [comment]
@phalodi Is there a better way to check **insert** & **delete** operations in Reactivemongo ? If yes then please add them.

**Comment by gupta-himanshu** [comment]
@phalodi Please move the Implicits at the Class level in **dbs/src/main/scala/com/knoldus/dbcrud/FindDoc.scala** file.

**Comment by gupta-himanshu** [comment]
@phalodi Can we have domain(case class) in a separate file ? If yes then please do it.

**Comment by phalodi** [comment]
i had separate out the case class,make implicits at class level and refactor the package name

**Comment by phalodi** [comment]
and i m working on how we check more better way insert and delete operation and i dont got much about  logback

**Comment by phalodi** [comment]
i had improve checks for the insert and delete operations with ok so please review it

**Comment by gupta-himanshu** [comment]
@phalodi Can we use **companion object** concept for providing implicits of domain (case class) ?

**Comment by phalodi** [comment]
yeah we can and i already have done it i make a companion object in People.scala file and remove it from CrudTest and FindDocTest

**Pull request closed without merging**
